### ISSUE TITLE
How to import/use this library?

### ISSUE THREAD

**Issue by mohsin363** [withplum/EmojiBottomSheetDialog#13]
Hi @cmargonis  @ChryssaAliferi 
how to /use this library in Android app?

Thanks,
Mohsin

**Comment by cmargonis** [comment]
Hello @mohsin363 ,
It can be imported in gradle via: `implementation("com.withplum:emojiBottomSheetDialog:1.1.0)`

Thanks for the question, we'll be updating the readme to include this part, as it got somehow missed.
