### ISSUE TITLE
Migrate to emoji2 and public api changes

### ISSUE THREAD

**Issue by cmargonis** [withplum/EmojiBottomSheetDialog#17]
## Background

1. Starting with emoji2 setting up and configuring emojis has become simpler (`androidx.startup.InitializationProvider` automatically initialises the library on app startup using a default emoji font provider).

2. Moreover, [AppCompat 1.4.0](https://developer.android.com/jetpack/androidx/releases/appcompat#version_140_3) includes a dependency and uses emoji2 library.

3. The public api of the library provides method that would be better removed as they're out of the scope of the library:
  - `initialize` method: Performs the same initialization that `emoji2` would do by default, with the additional supply of `EmojInitListener`. Emoji initialization would be best controlled by downstream users of the library.
  - `hasEmojiGlyph` mirrors utility function of `emoji2` with the same name. Would be best to let library users directly use the `emoji2` functionality.

## Proposed version 2.0 changes

- Use [emoji2](https://developer.android.com/guide/topics/ui/look-and-feel/emoji2#support-without-appcompat)
  - Convert `emoji2` dependencies from `api` -> `implementation`
- Remove `initialize` function
- Update documentation to clearly instruct on library's usage (downstream users can either get `emoji2` by using AppCompat 1.4 or by directly importing `emoji2` dependencies).
- Bump major version to `2.x`  as there will be breaking changes.

**Comment by cpaleop** [comment]
Looks good!

**Comment by cpaleop** [comment]
Would it be better to provide a PR with the transition to `emoji2` and handle the documentation and version updates in another PR?

**Comment by cmargonis** [comment]
> Would it be better to provide a PR with the transition to `emoji2` and handle the documentation and version updates in another PR?

Yeap!
